name: gnome-boxes
adopt-info: gnome-boxes
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /etc/mdevctl.d:
    bind: $SNAP/etc/mdevctl.d
  /usr/share/gnome-boxes:
    bind: $SNAP/usr/share/gnome-boxes
  /usr/share/osinfo:
    bind: $SNAP/usr/share/osinfo
  /usr/share/libosinfo/usb.ids:
    symlink: $SNAP/usr/share/misc/usb.ids
  /usr/share/misc/usb.ids:
    symlink: $SNAP/usr/share/misc/usb.ids
  /usr/share/libosinfo/pci.ids:
    symlink: $SNAP/usr/share/misc/pci.ids
  /usr/share/misc/pci.ids:
    symlink: $SNAP/usr/share/misc/pci.ids
  /usr/lib/$CRAFT_ARCH_TRIPLET/libvirt:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libvirt
  /usr/share/libvirt:
    bind: $SNAP/usr/share/libvirt
  /usr/lib/libvirt:
    bind: $SNAP/usr/lib/libvirt
  /usr/share/seabios:
    bind: $SNAP/usr/share/seabios
  /usr/lib/ipxe:
    bind: $SNAP/usr/lib/ipxe
  /usr/bin/qemu-system-x86_64:
    bind-file: $SNAP/usr/bin/qemu-system-x86_64
  /usr/sbin/dnsmasq:
    bind-file: $SNAP/usr/sbin/dnsmasq
  /usr/share/qemu:
    bind: $SNAP/usr/share/qemu
  /etc/libvirt:
    bind: $SNAP/etc/libvirt
  /usr/libexec/libvirt_iohelper:
    bind-file: $SNAP/usr/libexec/libvirt_iohelper
  /usr/sbin/smbd:
    bind-file: $SNAP/usr/sbin/smbd

slots:
  # for GtkApplication registration
  gnome-boxes:
    interface: dbus
    bus: session
    name: org.gnome.Boxes

apps:
  gnome-boxes:
    command: usr/bin/gnome-boxes
    command-chain: [ bin/launcher ]
    extensions: [gnome]
    plugs:
      - audio-record
      - audio-playback
      - camera
      - hardware-observe
      - home
      - kvm
      - login-session-observe
      - mount-observe
      - network
      - network-bind
      - network-status
      - opengl
      - process-control
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - system-observe
      - time-control
      - udisks2
      - unity7
      - upower-observe
    desktop: usr/share/applications/org.gnome.Boxes.desktop
    common-id: org.gnome.Boxes.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gnome-boxes
      GI_TYPELIB_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gnome-boxes/girepository-1.0:$GI_TYPELIB_PATH
      GTK_USE_PORTAL: '0'
      LIBVIRT_DEFAULT_URI: 'qemu+unix:///session'

  qemu-x86-virgil:
    extensions: [gnome]
    command: usr/bin/qemu-system-x86_64
    command-chain: [bin/runner]
    plugs:
      - audio-playback
      - audio-record
      - kvm
      - home
      - opengl
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
    environment:
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/ceph


parts:
  libraries:
    plugin: nil
    build-packages:
      - bison
      - flex
      - gettext
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libgtk-3-dev
      - libibverbs-dev
      - libjpeg8-dev
      - libncurses5-dev
      - libnuma-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libseccomp-dev
      - libsnappy-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxen-dev
      - liblzo2-dev
      - libx11-dev
      - libxml2-dev
      - libepoxy-dev
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - xfslibs-dev
      - zlib1g-dev
      - libnfs-dev
      - libiscsi-dev
      - libpulse-dev
      - bzip2
      - libgbm-dev
      - libepoxy-dev
      - libxslt1-dev
      - libarchive-dev
      - libgtk-vnc-2.0-dev
      - libusb-1.0-0-dev
      - cmake
      - libxml2-dev
      - libncurses5-dev
      - libreadline-dev
      - zlib1g-dev
      - libgcrypt20-dev
      - libgnutls28-dev
      - libsasl2-dev
      - libxen-dev
      - libparted-dev
      - libdevmapper-dev
      - uuid-dev
      - libudev-dev
      - libpciaccess-dev
      - libcurl4-gnutls-dev
      - libpolkit-gobject-1-dev
      - libcap-ng-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libyajl-dev
      - libpcap0.8-dev
      - libnuma-dev
      - libsanlock-dev
      - libaudit-dev
      - libselinux1-dev
      - libapparmor-dev
      - libdbus-1-dev
      - systemtap-sdt-dev
      - libzfslinux-dev
      - librbd-dev
      - librados-dev
      - libglusterfs-dev
      - libwireshark-dev
      - libwiretap-dev
      - libfuse-dev
      - python3-docutils
      - xsltproc
      - libopus-dev
      - python3-pip
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - liblz4-dev
      - asciidoc
    stage-packages:
      - mdevctl
      - dnsmasq
      - libasn1-8-heimdal
      - libcacard0
      - libcurl3-gnutls
      - libfdt1
      - libgssapi3-heimdal
      - libgtk-vnc-2.0-0
      - libgvnc-1.0-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.5-0
      - libnghttp2-14
      - libnspr4
      - libnss3
      - libnuma1
      - libopus0
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libusb-1.0-0
      - libusbredirhost1
      - libusbredirparser1
      - libva-x11-2
      - libwind0-heimdal
      - libxslt1.1
      - libyajl2
      - pci.ids
      - usb.ids
      - libaio1
      - libbluetooth3
      - libboost-iostreams1.74.0
      - libboost-random1.74.0
      - libboost-thread1.74.0
      - libbrlapi0.8
      - libflac8
      - libiscsi7
      - libnfs13
      - libnuma1
      - librados2
      - librbd1
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsnappy1v5
      - libsndio7.0
      - libusb-1.0-0
      - libusbredirparser1
      - libvdeplug2
      - libxencall1
      - libxenstore4
      - libxi6
      - libxss1
      - libacl1
      - libapparmor1
      - libaudit1
      - libblkid1
      - libcap-ng0
      - libcurl3-gnutls
      - libdbus-1-3
      - libdevmapper1.02.1
      - libfuse2
      - libgcc-s1
      - libgfapi0
      - libgfrpc0
      - libgfxdr0
      - libglib2.0-0
      - libglusterfs0
      - libgnutls30
      - libnl-3-200
      - libnuma1
      - libparted2
      - libpcap0.8
      - librados2
      - librbd1
      - libsanlock-client1
      - libsasl2-2
      - libselinux1
      - libtirpc3
      - libudev1
      - libxencall1
      - libxenmisc4.16
      - libxendevicemodel1
      - libxenevtchn1
      - libxenforeignmemory1
      - libxengnttab1
      - libxenstore4
      - libxentoolcore1
      - libxentoollog1
      - libxml2
      - libyajl2
      - samba
  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      craftctl default
      rm -f $CRAFT_PRIME/usr/lib/x86_64-linux-gnu/libva-x11.so.2
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current"
        find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done

  libvirt:
    source: https://gitlab.com/libvirt/libvirt.git
    after: [ qemu, libraries, libraries ]
    source-tag: 'v9.4.0'
    source-depth: 1
    plugin: meson
    build-environment:
      - CFLAGS: "-Wno-error"
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dexpensive_tests=disabled
#    override-build: |
#      git apply $CRAFT_PROJECT_DIR/patches/libvirt-qemu.patch
#      mkdir build && cd build
#      ../autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-qemu
#      make
#      DESTDIR=$CRAFT_PART_INSTALL make install

  libvirt-glib:
    source: https://github.com/libvirt/libvirt-glib.git
    after: [ libvirt, libraries ]
    source-depth: 1
    source-tag: 'v4.0.0'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release

  spice-protocol:
    source: https://gitlab.freedesktop.org/spice/spice-protocol.git
    source-tag: 'v0.14.4'
    source-depth: 1
    plugin: meson
    after: [ libraries ]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release

  spice-gtk:
    after: [ libphodav, spice-protocol, libraries ]
    source: https://gitlab.freedesktop.org/spice/spice-gtk.git
    source-tag: 'v0.42'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dgtk=enabled
      - -Dwayland-protocols=enabled
      - -Dintrospection=enabled
    override-build: |
      python3 -m pip install six pyparsing asciidoc
      craftctl default

  spice-server:
    after: [ libphodav, spice-protocol, spice-gtk, libraries ]
    source: https://gitlab.freedesktop.org/spice/spice.git
    source-tag: 'v0.15.2'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dmanual=false
      - -Dtests=false

  tracker:
    after: [ spice-gtk, libraries ]
    source: https://gitlab.gnome.org/GNOME/tracker.git
    source-tag: '3.5.3'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Ddocs=false
      - -Dman=false
      - -Dbash_completion=false
      - -Dsystemd_user_services=false
      - -Dtest_utils=false
      - -Dintrospection=enabled
    override-pull: |
      set -eux
      craftctl default
      # disabling man and docs seems to be ignored by meson
      sed -i "s#subdir('docs')##g" meson.build

  libosinfo:
    after: [ libvirt-glib, tracker, libraries ]
    source: https://gitlab.com/libosinfo/libosinfo.git
    source-tag: 'v1.10.0'
    source-depth: 1
    plugin: meson
    override-pull: |
      set -eux
      craftctl default
      git apply $CRAFT_PROJECT_DIR/patches/libosinfo.patch
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Denable-gtk-doc=false
      - -Denable-tests=false
      - -Dlibsoup-abi=3.0

  gnome-boxes:
    after: [ libvirt-glib, tracker, libosinfo, libraries ]
    source: https://gitlab.gnome.org/GNOME/gnome-boxes.git
    source-depth: 1
    source-tag: '44.2'
    parse-info: [usr/share/metainfo/org.gnome.Boxes.appdata.xml]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Ddistributor_name=Ubuntu
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      sed -i.bak -e "s|symlink_media: true|symlink_media: false|g" $CRAFT_PART_SRC/help/meson.build
      # Ensure we save VMs in $SNAP_USER_COMMON
      git apply $CRAFT_PROJECT_DIR/patches/gnome-boxes-snap-user-common.patch
      # Update recommended downloads
      # git apply $CRAFT_PROJECT_DIR/patches/gnome-boxes-recommended-downloads.patch
    build-environment:
      - C_INCLUDE_PATH: ${C_INCLUDE_PATH:+$C_INCLUDE_PATH:}$CRAFT_STAGE/usr/include/libvirt-gconfig-1.0:$CRAFT_STAGE/usr/include/libvirt-glib-1.0:$CRAFT_STAGE/usr/include/libvirt-gobject-1.0:$CRAFT_STAGE/usr/include/libosinfo-1.0
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH


  libphodav:
    after: [ libraries, libraries ]
    source: https://gitlab.gnome.org/GNOME/phodav.git
    source-tag: 'v3.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dgtk_doc=disabled

  virgl:
    after: [ libraries, libraries ]
    source: https://gitlab.freedesktop.org/virgl/virglrenderer.git
    source-tag: '0.10.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release

  qemu:
    after: [ virgl, spice-server ]
    source: https://gitlab.com/qemu-project/qemu.git
    source-tag: 'v6.0.0'
    # version 8 added use of USERFAULTFD_IOC_NEW kernel interface, which isn't
    # available in ubuntu < 23.04.
    # version 7.2.2 use KVM_CAP_X86_TRIPLE_FAULT_EVENT, which is also quite recent.
    # version 7.0.0 requires KVM_GET_XSAVE2, which is also quite recent.
# ext:updatesnap
#   version-format:
#     lower-than: 6.1.0
    source-depth: 1
    plugin: nil
    override-build: |
      cd ..
      rm -rf $CRAFT_PART_BUILD
      mkdir -p $CRAFT_PART_BUILD
      cd $CRAFT_PART_BUILD
      cp -a $CRAFT_PART_SRC/* $CRAFT_PART_BUILD/
      cp /usr/include/linux/userfaultfd.h ./include/qemu/
      ./configure --prefix=/usr --target-list=x86_64-softmmu,aarch64-softmmu,arm-softmmu --audio-drv-list=pa,sdl --enable-libusb --enable-usb-redir --enable-sdl --enable-spice --disable-werror
      cd build
      make -j8
      make DESTDIR=$CRAFT_PART_INSTALL install

  runner:
    after: [ qemu ]
    source: .
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av runner $SNAPCRAFT_PART_INSTALL/bin/

  smbd:
    after: [ runner ]
    plugin: nil
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc-binding.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdcerpc-server.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjansson.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldb.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-krb5pac.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-nbt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libndr-standard.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libnetapi.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpopt.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpython2.7.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpytalloc-util.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamba-*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamdb.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsmbconf.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsmbldap.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtalloc.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtevent.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libtevent-util.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwbclient.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba/*
      - usr/sbin/smbd

  launcher:
    plugin: dump
    after: [ qemu, libraries ]
    source: scripts
    organize:
      launcher.sh: bin/launcher
